version: '3.9'

services:
  app:
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=LocalDB;UId=sa;Password=Password123;Trusted_Connection=False
    depends_on:
      - sqlserver
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend/src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork

volumes:
  sql_data:

networks:
  mynetwork:
    driver: bridge